//! `AndroidManifest.xml` for the NativeActivity APK.
//!
//! Ported byte-for-byte from labelle-cli `src/cli/android/package.zig`
//! (`generateAndroidManifest`, development 23aa180; labelle-cli#405). Two
//! changes: the inputs come from `providers/android.json` and
//! `project.labelle` instead of the CLI's `AndroidConfig`, and
//! `versionCode`/`versionName` are parameters (the CLI always wrote `1` and
//! `"1.0"`; `labelle bundle --build-number=N` now stamps `N`). With the
//! defaults (`1`, `"1.0"`) the output is identical to the CLI's.
//!
//! The manifest is backend-neutral: `android.app.NativeActivity` loading
//! `libgame.so` (`android.app.lib_name = game`). Only the bgfx backend is
//! verified through this packager so far.
const std = @import("std");
const settings_mod = @import("../settings.zig");
const icon = @import("icon.zig");

pub const Inputs = struct {
    package_name: []const u8,
    /// The launcher label (`app_name`, else the project title).
    app_name: []const u8,
    min_sdk_version: u32 = settings_mod.min_sdk_floor,
    target_sdk_version: u32 = settings_mod.default_target_sdk,
    orientation: settings_mod.Orientation = .all,
    /// project.labelle `.android.immersive_mode` (assembler-owned).
    immersive_mode: bool = false,
    debuggable: bool = false,
    version_code: u32 = 1,
    version_name: []const u8 = "1.0",
    /// Whether `icon.stage` wrote `res/mipmap-*/ic_launcher.png`.
    has_launcher_icon: bool = false,
    /// `providers/android.json` `renderer` (labelle-bgfx#172 D2/D7); the
    /// settings default, `auto`, when the key is absent.
    renderer: settings_mod.Renderer = settings_mod.default_renderer,
};

/// The optional Vulkan 1.1 feature (D7). `0x401000` is
/// `VK_MAKE_API_VERSION(0, 1, 1, 0)`. `required="false"` keeps the app
/// installable on GLES-only devices: GLES 3.0 stays the required fallback.
pub const vulkan_feature_line =
    "\n    <uses-feature android:name=\"android.hardware.vulkan.version\" android:version=\"0x401000\" android:required=\"false\" />";

/// The `<application>` meta-data name the runtime reads at launch to pick a
/// renderer (labelle-android#27). It is written for every value, `gles`
/// included, so the runtime never has to guess (an APK without it gets the
/// runtime's default, `auto`, the same as the settings default).
pub const renderer_meta_name = "labelle.renderer";

/// The Android `android:screenOrientation` value for `o`.
pub fn screenOrientation(o: settings_mod.Orientation) []const u8 {
    return switch (o) {
        .portrait => "portrait",
        .landscape => "landscape",
        .sensor_landscape => "sensorLandscape",
        .all => "unspecified",
    };
}

/// Generate AndroidManifest.xml for NativeActivity. Caller owns the text.
///
/// `has_launcher_icon` says whether `icon.stage` wrote
/// `res/mipmap-*/ic_launcher.png` into the staging tree. The attribute is
/// emitted only when it did: `android:icon` pointing at a resource that
/// isn't in the APK is an aapt link error, and the resource is absent for
/// projects generated by an assembler older than the one that ships
/// `default_icon.png`.
pub fn generate(allocator: std.mem.Allocator, in: Inputs) ![]u8 {
    const orientation = screenOrientation(in.orientation);

    // Immersive mode: launch fullscreen with the status bar + title bar
    // hidden via the built-in `Theme.NoTitleBar.Fullscreen` framework
    // theme. That's a framework resource, so it costs the APK nothing.
    // Note: this hides the status bar only, NOT the navigation bar;
    // immersive-sticky nav-bar hiding is the runtime's job.
    const theme_attr: []const u8 = if (in.immersive_mode)
        "\n            android:theme=\"@android:style/Theme.NoTitleBar.Fullscreen\""
    else
        "";

    // Launcher icon (cli#340): the mipmaps staged by `icon.zig` are the only
    // compiled resources in the APK, which is why the packager hands aapt a
    // `-S <staging>/res`. `android:hasCode="false"` is unaffected —
    // resources are not code.
    const icon_attr: []const u8 = if (in.has_launcher_icon)
        " android:icon=\"" ++ icon.icon_resource_ref ++ "\""
    else
        "";

    // Debuggable (labelle-assembler#737). OFF unless the settings opt in, so
    // a release APK's manifest never carries it. It is what makes the
    // platform honour `setprop wrap.<package>` and what lets `run-as` read a
    // capture back out of the app's private files dir.
    const debuggable_attr: []const u8 = if (in.debuggable)
        " android:debuggable=\"true\""
    else
        "";

    // D7: advertise Vulkan only when the APK may ask for it.
    const vulkan_feature: []const u8 = switch (in.renderer) {
        .gles => "",
        .vulkan, .auto => vulkan_feature_line,
    };

    return std.fmt.allocPrint(allocator,
        \\<?xml version="1.0" encoding="utf-8"?>
        \\<manifest xmlns:android="http://schemas.android.com/apk/res/android"
        \\    package="{s}"
        \\    android:versionCode="{d}"
        \\    android:versionName="{s}">
        \\
        \\    <uses-sdk android:minSdkVersion="{d}" android:targetSdkVersion="{d}" />
        \\    <uses-feature android:glEsVersion="0x00030000" android:required="true" />{s}
        \\    <uses-feature android:name="android.hardware.gamepad" android:required="false" />
        \\
        \\    <application android:hasCode="false" android:label="{s}"{s}{s}>
        \\        <meta-data android:name="labelle.renderer" android:value="{s}" />
        \\        <activity android:name="android.app.NativeActivity"
        \\            android:configChanges="orientation|keyboardHidden|screenSize"
        \\            android:screenOrientation="{s}"{s}
        \\            android:exported="true">
        \\            <meta-data android:name="android.app.lib_name" android:value="game" />
        \\            <intent-filter>
        \\                <action android:name="android.intent.action.MAIN" />
        \\                <category android:name="android.intent.category.LAUNCHER" />
        \\            </intent-filter>
        \\        </activity>
        \\    </application>
        \\</manifest>
        \\
    , .{
        try xmlEscape(allocator, in.package_name),
        in.version_code,
        try xmlEscape(allocator, try androidString(allocator, in.version_name)),
        in.min_sdk_version,
        in.target_sdk_version,
        vulkan_feature,
        try xmlEscape(allocator, try androidString(allocator, in.app_name)),
        icon_attr,
        debuggable_attr,
        in.renderer.value(),
        orientation,
        theme_attr,
    });
}

/// Encode `text` as an Android string literal, the way aapt reads a
/// string attribute once the XML parser is done with it: a leading `@` or
/// `?` would make it a resource / theme-attribute reference (`@Home` fails
/// to link), an unescaped `'` is an aapt error ("Apostrophe not preceded
/// by \\"), an unescaped `"` starts a quoted run and is dropped, and `\\`
/// starts an escape. Each gets a backslash. Text with none of them (every
/// name the CLI could package) is returned unchanged; the result is then
/// XML-escaped by `xmlEscape`.
fn androidString(allocator: std.mem.Allocator, text: []const u8) ![]const u8 {
    const sigil = text.len > 0 and (text[0] == '@' or text[0] == '?');
    if (!sigil and std.mem.indexOfAny(u8, text, "\\'\"") == null) return text;
    var out: std.ArrayList(u8) = .empty;
    if (sigil) try out.append(allocator, '\\');
    for (text) |ch| {
        if (ch == '\\' or ch == '\'' or ch == '"') try out.append(allocator, '\\');
        try out.append(allocator, ch);
    }
    return out.toOwnedSlice(allocator);
}

/// Escape the five XML-special characters of an attribute value. The CLI
/// interpolated raw text; a label like `Tom & Jerry` would have been an
/// aapt parse error. Text without those characters is returned unchanged,
/// so every manifest the CLI could build is byte-identical. The result
/// is allocated in `allocator` (the caller's arena).
fn xmlEscape(allocator: std.mem.Allocator, text: []const u8) ![]const u8 {
    if (std.mem.indexOfAny(u8, text, "&<>\"'") == null) return text;
    var out: std.ArrayList(u8) = .empty;
    for (text) |ch| switch (ch) {
        '&' => try out.appendSlice(allocator, "&amp;"),
        '<' => try out.appendSlice(allocator, "&lt;"),
        '>' => try out.appendSlice(allocator, "&gt;"),
        '"' => try out.appendSlice(allocator, "&quot;"),
        '\'' => try out.appendSlice(allocator, "&apos;"),
        else => try out.append(allocator, ch),
    };
    return out.toOwnedSlice(allocator);
}

// ── Tests ─────────────────────────────────────────────────────────────────

const base: Inputs = .{ .package_name = "com.test.game", .app_name = "Test" };

fn with(comptime field: []const u8, value: anytype) Inputs {
    var in = base;
    @field(in, field) = value;
    return in;
}

/// The CLI's manifest for `package_name = "com.labelle.flying_platform"`,
/// `app_name = "Flying Platform"`, `orientation = .landscape`,
/// `immersive_mode = true`, a staged icon and every other key at its
/// default — byte-for-byte what labelle-cli 1.75 packages for Flying
/// Platform.
const fp_manifest =
    \\<?xml version="1.0" encoding="utf-8"?>
    \\<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    \\    package="com.labelle.flying_platform"
    \\    android:versionCode="1"
    \\    android:versionName="1.0">
    \\
    \\    <uses-sdk android:minSdkVersion="28" android:targetSdkVersion="34" />
    \\    <uses-feature android:glEsVersion="0x00030000" android:required="true" />
    \\    <uses-feature android:name="android.hardware.gamepad" android:required="false" />
    \\
    \\    <application android:hasCode="false" android:label="Flying Platform" android:icon="@mipmap/ic_launcher">
    \\        <activity android:name="android.app.NativeActivity"
    \\            android:configChanges="orientation|keyboardHidden|screenSize"
    \\            android:screenOrientation="landscape"
    \\            android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
    \\            android:exported="true">
    \\            <meta-data android:name="android.app.lib_name" android:value="game" />
    \\            <intent-filter>
    \\                <action android:name="android.intent.action.MAIN" />
    \\                <category android:name="android.intent.category.LAUNCHER" />
    \\            </intent-filter>
    \\        </activity>
    \\    </application>
    \\</manifest>
    \\
;

const gles_meta_line = "        <meta-data android:name=\"" ++ renderer_meta_name ++ "\" android:value=\"gles\" />\n";

fn fpInputs(renderer: settings_mod.Renderer) Inputs {
    return .{
        .package_name = "com.labelle.flying_platform",
        .app_name = "Flying Platform",
        .orientation = .landscape,
        .immersive_mode = true,
        .has_launcher_icon = true,
        .renderer = renderer,
    };
}

test "explicit gles reproduces the CLI's manifest plus only the gles renderer meta-data" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const xml = try generate(a, fpInputs(.gles));
    // gles is written too: the runtime never guesses.
    try std.testing.expectEqual(@as(usize, 1), std.mem.count(u8, xml, gles_meta_line));
    // The meta-data is the first child of <application>, not in <activity>.
    const app_open_end = std.mem.indexOfPos(u8, xml, std.mem.indexOf(u8, xml, "<application").?, ">\n").?;
    try std.testing.expectEqual(app_open_end + 2, std.mem.indexOf(u8, xml, gles_meta_line).?);
    // No Vulkan feature with gles (D7).
    try std.testing.expect(std.mem.indexOf(u8, xml, "vulkan") == null);
    // Otherwise byte-identical to the CLI's manifest.
    const stripped = try std.mem.replaceOwned(u8, a, xml, gles_meta_line, "");
    try std.testing.expectEqualStrings(fp_manifest, stripped);
}

test "vulkan and auto add the optional Vulkan 1.1 feature and keep GLES 3.0 required" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const gles = try generate(a, fpInputs(.gles));
    const feature = "<uses-feature android:name=\"android.hardware.vulkan.version\" android:version=\"0x401000\" android:required=\"false\" />";
    const gles_feature = "<uses-feature android:glEsVersion=\"0x00030000\" android:required=\"true\" />";
    inline for (.{ settings_mod.Renderer.vulkan, settings_mod.Renderer.auto }) |renderer| {
        const xml = try generate(a, fpInputs(renderer));
        try std.testing.expectEqual(@as(usize, 1), std.mem.count(u8, xml, feature));
        try std.testing.expectEqual(@as(usize, 1), std.mem.count(u8, xml, gles_feature));
        // Top-level, right after the GLES feature (outside <application>).
        try std.testing.expect(std.mem.indexOf(u8, xml, gles_feature ++ vulkan_feature_line) != null);
        const meta = "        <meta-data android:name=\"" ++ renderer_meta_name ++ "\" android:value=\"" ++ @tagName(renderer) ++ "\" />\n";
        try std.testing.expectEqual(@as(usize, 1), std.mem.count(u8, xml, meta));
        // Only those two lines differ from the gles manifest.
        const no_feature = try std.mem.replaceOwned(u8, a, xml, vulkan_feature_line, "");
        const as_gles = try std.mem.replaceOwned(u8, a, no_feature, meta, gles_meta_line);
        try std.testing.expectEqualStrings(gles, as_gles);
    }
}

/// Settings → manifest inputs the way `package.zig` maps them.
fn inputsFromSettings(s: settings_mod.Settings) Inputs {
    var in = fpInputs(s.renderer);
    in.package_name = s.package_name;
    return in;
}

test "default (no renderer key) is auto: the manifest has the optional Vulkan feature and auto meta-data (#30)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    var diag: settings_mod.Diagnostic = .{};
    const s = try settings_mod.parse(a, "{\"schema_version\": 1, \"package_name\": \"com.labelle.flying_platform\"}", &diag);
    // The mechanism: the key is absent, so the field default applied, and
    // that default is `auto`, for both the settings and the bare Inputs.
    try std.testing.expectEqual(settings_mod.Renderer.auto, settings_mod.default_renderer);
    try std.testing.expectEqual(settings_mod.default_renderer, s.renderer);
    try std.testing.expectEqual(settings_mod.default_renderer, (Inputs{ .package_name = "", .app_name = "" }).renderer);

    const xml = try generate(a, inputsFromSettings(s));
    const auto_meta = "        <meta-data android:name=\"" ++ renderer_meta_name ++ "\" android:value=\"auto\" />\n";
    try std.testing.expectEqual(@as(usize, 1), std.mem.count(u8, xml, auto_meta));
    try std.testing.expectEqual(@as(usize, 1), std.mem.count(u8, xml, vulkan_feature_line));
    // Exactly the explicit-auto manifest.
    try std.testing.expectEqualStrings(try generate(a, fpInputs(.auto)), xml);
    // And, minus those two lines, the CLI's (gles-era) manifest.
    const no_feature = try std.mem.replaceOwned(u8, a, xml, vulkan_feature_line, "");
    const stripped = try std.mem.replaceOwned(u8, a, no_feature, auto_meta, "");
    try std.testing.expectEqualStrings(fp_manifest, stripped);
}

test "explicit gles in providers/android.json: the old manifest, no Vulkan feature (#30 opt-out)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    var diag: settings_mod.Diagnostic = .{};
    const s = try settings_mod.parse(a, "{\"schema_version\": 1, \"package_name\": \"com.labelle.flying_platform\", \"renderer\": \"gles\"}", &diag);
    try std.testing.expectEqual(settings_mod.Renderer.gles, s.renderer);
    const xml = try generate(a, inputsFromSettings(s));
    try std.testing.expect(std.mem.indexOf(u8, xml, "vulkan") == null);
    const stripped = try std.mem.replaceOwned(u8, a, xml, gles_meta_line, "");
    try std.testing.expectEqualStrings(fp_manifest, stripped);
}

test "omits android:debuggable unless the settings opt in (#737)" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const release = try generate(a, base);
    try std.testing.expect(std.mem.indexOf(u8, release, "debuggable") == null);
    const debuggable = try generate(a, with("debuggable", true));
    // On <application>, not on <activity>: `wrap.<package>` is honoured per
    // APPLICATION, and `run-as` keys off the application flag too.
    try std.testing.expect(std.mem.indexOf(u8, debuggable, "<application android:hasCode=\"false\" android:label=\"Test\" android:debuggable=\"true\">") != null);
    // The only difference is that one attribute — nothing else drifts.
    const stripped = try std.mem.replaceOwned(u8, a, debuggable, " android:debuggable=\"true\"", "");
    try std.testing.expectEqualStrings(release, stripped);
}

test "omits the theme attribute when immersive_mode is false" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const xml = try generate(arena.allocator(), base);
    try std.testing.expect(std.mem.indexOf(u8, xml, "android:theme=") == null);
}

test "adds the NoTitleBar.Fullscreen theme on <activity> when immersive_mode is true" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const xml = try generate(arena.allocator(), with("immersive_mode", true));
    try std.testing.expect(std.mem.indexOf(u8, xml, "android:theme=\"@android:style/Theme.NoTitleBar.Fullscreen\"") != null);
    const activity_start = std.mem.indexOf(u8, xml, "<activity") orelse return error.TestUnexpectedResult;
    const activity_open_end = std.mem.indexOfPos(u8, xml, activity_start, ">") orelse return error.TestUnexpectedResult;
    const theme_idx = std.mem.indexOf(u8, xml, "android:theme=") orelse return error.TestUnexpectedResult;
    try std.testing.expect(theme_idx > activity_start and theme_idx < activity_open_end);
}

test "advertises the gamepad as an optional feature" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const xml = try generate(arena.allocator(), base);
    try std.testing.expect(std.mem.indexOf(u8, xml, "<uses-feature android:name=\"android.hardware.gamepad\" android:required=\"false\" />") != null);
}

test "points <application> at the staged launcher icon" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const xml = try generate(arena.allocator(), with("has_launcher_icon", true));
    // On <application>, not <activity>: an activity-level icon shows in the
    // task switcher but leaves the launcher on the stock robot (cli#340).
    const app_start = std.mem.indexOf(u8, xml, "<application") orelse return error.TestUnexpectedResult;
    const app_open_end = std.mem.indexOfPos(u8, xml, app_start, ">") orelse return error.TestUnexpectedResult;
    const icon_idx = std.mem.indexOf(u8, xml, "android:icon=\"@mipmap/ic_launcher\"") orelse return error.TestUnexpectedResult;
    try std.testing.expect(icon_idx > app_start and icon_idx < app_open_end);
}

test "omits android:icon when no icon was staged" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const xml = try generate(arena.allocator(), base);
    try std.testing.expect(std.mem.indexOf(u8, xml, "android:icon=") == null);
    try std.testing.expect(std.mem.indexOf(u8, xml, "android:hasCode=\"false\"") != null);
}

test "maps every Orientation to its android:screenOrientation value" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    inline for (.{
        .{ settings_mod.Orientation.portrait, "portrait" },
        .{ settings_mod.Orientation.landscape, "landscape" },
        .{ settings_mod.Orientation.sensor_landscape, "sensorLandscape" },
        .{ settings_mod.Orientation.all, "unspecified" },
    }) |case| {
        const xml = try generate(arena.allocator(), with("orientation", case[0]));
        try std.testing.expect(std.mem.indexOf(u8, xml, "android:screenOrientation=\"" ++ case[1] ++ "\"") != null);
    }
}

test "versionCode and versionName are stamped from the inputs" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var in = base;
    in.version_code = 42;
    in.version_name = "2.3.1";
    const xml = try generate(arena.allocator(), in);
    try std.testing.expect(std.mem.indexOf(u8, xml, "android:versionCode=\"42\"\n    android:versionName=\"2.3.1\">") != null);
}

test "attribute text is XML-escaped; plain text is untouched" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const xml = try generate(a, with("app_name", "Tom & Jerry <3"));
    try std.testing.expect(std.mem.indexOf(u8, xml, "android:label=\"Tom &amp; Jerry &lt;3\"") != null);
    const plain = "Flying Platform";
    try std.testing.expect((try xmlEscape(a, plain)).ptr == plain.ptr);
}

test "app_name and version_name are Android string literals: sigils, quotes and backslashes escaped" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const cases = [_][2][]const u8{
        // A leading @/? is a reference to aapt; later ones are plain text.
        .{ "@Home", "\\@Home" },
        .{ "?attr", "\\?attr" },
        .{ "Tom@Home?", "Tom@Home?" },
        // Apostrophes and quotes: backslash (aapt), then the XML entity.
        .{ "it's", "it\\&apos;s" },
        .{ "say \"hi\"", "say \\&quot;hi\\&quot;" },
        .{ "a\\b", "a\\\\b" },
        .{ "", "" },
    };
    for (cases) |c| {
        const label = try generate(a, with("app_name", c[0]));
        const want_label = try std.fmt.allocPrint(a, "android:label=\"{s}\"", .{c[1]});
        try std.testing.expect(std.mem.indexOf(u8, label, want_label) != null);
        const version = try generate(a, with("version_name", c[0]));
        const want_version = try std.fmt.allocPrint(a, "android:versionName=\"{s}\">", .{c[1]});
        try std.testing.expect(std.mem.indexOf(u8, version, want_version) != null);
    }
    // A normal name is untouched (the FP manifest test above stays byte-identical).
    const plain = "Flying Platform";
    try std.testing.expect((try androidString(a, plain)).ptr == plain.ptr);
}
